# Chương 3 - Bài tập

## Giới thiệu Keras và TensorFlow

MSSV:   
Họ tên sinh viên: 


## Mục tiêu thực hành

Sau khi hoàn thành notebook này, sinh viên có thể:

- Làm việc với tensor và `tf.Variable` trong TensorFlow.
- Thực hiện một số phép toán tensor cơ bản.
- Sử dụng `tf.GradientTape()` để tính gradient.
- Xây dựng mô hình Keras đơn giản.
- Compile, train, evaluate và predict với mô hình Keras.

## Yêu cầu

Sinh viên đọc kỹ yêu cầu từng bài, hoàn thiện phần code còn thiếu và chạy kết quả.

Lưu ý: Chỉ điền code vào các ô code. Không xóa phần mô tả bài tập.

## Bài 1. Import thư viện cần thiết

Yêu cầu:

1. Import TensorFlow với bí danh `tf`.
2. Import NumPy với bí danh `np`.
3. Import Keras và `layers` từ TensorFlow.
4. In ra phiên bản TensorFlow đang sử dụng.

In [2]:
# TODO: Import các thư viện cần thiết
import tensorflow as tf
import numpy as np
from tensorflow.keras import layers
from tensorflow import keras

# TODO: In ra phiên bản TensorFlow
print(tf.__version__)


2026-04-09 16:28:17.012330: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-04-09 16:28:17.106955: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-04-09 16:28:18.814760: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.


2.20.0


## Bài 2. Tạo tensor hằng và quan sát thuộc tính

Yêu cầu:

1. Tạo tensor `a` có giá trị `[[1.0, 2.0], [3.0, 4.0]]`.
2. In tensor `a`.
3. In shape của `a`.
4. In dtype của `a`.

In [26]:
# TODO: Tạo tensor hằng a
a = tf.constant([[1.0, 2.0], [3.0, 4.0]])

# TODO: In tensor a
print(a)

# TODO: In shape của a
print(a.shape)

# TODO: In dtype của a
print(a.dtype)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
(2, 2)
<dtype: 'float32'>


## Bài 3. Làm việc với `tf.Variable`

Yêu cầu:

1. Tạo biến `v` với giá trị khởi tạo là một tensor ngẫu nhiên kích thước `(2, 2)`.
2. In giá trị ban đầu của `v`.
3. Gán toàn bộ phần tử của `v` thành 1.
4. Cộng thêm 1 vào toàn bộ phần tử của `v`.
5. In giá trị cuối cùng của `v`.

In [27]:
# TODO: Tạo biến v với giá trị khởi tạo ngẫu nhiên shape=(2, 2)
v = tf.Variable(tf.random.uniform(shape=(2, 2)))

# TODO: In giá trị ban đầu của v
print(v)

# TODO: Gán toàn bộ phần tử của v thành 1
v.assign(tf.ones_like(v))

# TODO: Cộng thêm 1 vào toàn bộ phần tử của v
v.assign_add(tf.ones_like(v))

# TODO: In giá trị cuối cùng của v
print(v)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0.6983634 , 0.04020286],
       [0.23700106, 0.02998352]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>


## Bài 4. Thực hiện các phép toán tensor cơ bản

Yêu cầu:

Cho hai tensor:

- `x = [[1.0, 2.0], [3.0, 4.0]]`
- `y = [[5.0, 6.0], [7.0, 8.0]]`

Hãy thực hiện và in kết quả của các phép toán sau:

1. Cộng tensor `x + y`
2. Bình phương từng phần tử của `x`
3. Nhân ma trận `x` với `y`
4. Lấy giá trị lớn hơn theo từng phần tử giữa `x` và `y`

In [28]:
# TODO: Tạo tensor x và y
x = tf.constant([[1.0, 2.0], [3.0, 4.0]])
y = tf.constant([[5.0, 6.0], [7.0, 8.0]])

# TODO: Thực hiện phép cộng x + y
print("Addition of x and y:", tf.add(x, y))
print("-"*50)
# TODO: Thực hiện tf.square(x)
print("Square of x:", tf.square(x))
print("-"*50)
# TODO: Thực hiện tf.matmul(x, y)
print("Matmul of x and y:", tf.matmul(x, y))
print("-"*50)
# TODO: Thực hiện tf.maximum(x, y)
print("Maximum of x and y:", tf.maximum(x, y))

Addition of x and y: tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)
--------------------------------------------------
Square of x: tf.Tensor(
[[ 1.  4.]
 [ 9. 16.]], shape=(2, 2), dtype=float32)
--------------------------------------------------
Matmul of x and y: tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)
--------------------------------------------------
Maximum of x and y: tf.Tensor(
[[5. 6.]
 [7. 8.]], shape=(2, 2), dtype=float32)


## Bài 5. Tính gradient bằng `tf.GradientTape()`

Yêu cầu:

1. Tạo biến `w = 3.0` bằng `tf.Variable`.
2. Xét hàm `y = w^2 + 2w + 1`.
3. Dùng `tf.GradientTape()` để tính gradient `dy/dw`.
4. In ra giá trị của `y` và gradient thu được.

In [29]:
# TODO: Tạo biến w
w = tf.Variable(3.0)

# TODO: Dùng GradientTape để tính y và gradient dy/dw
with tf.GradientTape() as tape:
    y = w**2 + 2*w + 1

# TODO: In ra giá trị y
print("Value of y:", y.numpy())

# TODO: In ra gradient dy/dw
print("Gradient dy/dw:", tape.gradient(y, w).numpy())

Value of y: 16.0
Gradient dy/dw: 8.0


## Bài 6. Mô phỏng gradient descent đơn giản

Yêu cầu:

Xét hàm mất mát: $loss = (w - 4.0)^2$

Thực hiện gradient descent trong 10 bước để cập nhật `w` sao cho `w` tiến dần về 4.

Yêu cầu cụ thể:

1. Khởi tạo `w = 0.0`
2. Đặt `learning_rate = 0.1`
3. Lặp 10 bước
4. Mỗi bước in ra: số bước, giá trị `w`, giá trị `loss`, gradient

In [30]:
# TODO: Khởi tạo w và learning_rate
w = tf.Variable(0.0)
learning_rate = 0.1

# TODO: Viết vòng lặp gradient descent 10 bước
for step in range(10):
    with tf.GradientTape() as tape:
        loss = (w - 4.0)**2
    dy_dw = tape.gradient(loss, w)
    w.assign_sub(learning_rate * dy_dw)
    print(f"Step {step+1}: w = {w.numpy()}, loss = {loss.numpy()}")


Step 1: w = 0.800000011920929, loss = 16.0
Step 2: w = 1.440000057220459, loss = 10.239999771118164
Step 3: w = 1.9520001411437988, loss = 6.553599834442139
Step 4: w = 2.361600160598755, loss = 4.194303512573242
Step 5: w = 2.6892800331115723, loss = 2.684354066848755
Step 6: w = 2.9514241218566895, loss = 1.717986822128296
Step 7: w = 3.1611392498016357, loss = 1.0995113849639893
Step 8: w = 3.328911304473877, loss = 0.7036873698234558
Step 9: w = 3.4631290435791016, loss = 0.4503600299358368
Step 10: w = 3.5705032348632812, loss = 0.28823041915893555


## Bài 7. Xây dựng mô hình Keras đơn giản

Yêu cầu:

Tạo mô hình `Sequential` gồm:

1. Một layer `Dense` có 16 neuron, activation=`relu`, input shape = `(8,)`
2. Một layer output `Dense` có 1 neuron, activation=`sigmoid`
3. Hiển thị `model.summary()`

In [31]:
# TODO: Tạo mô hình Sequential theo yêu cầu
model = keras.Sequential([
    layers.Dense(16, activation='relu', input_shape=(8,)),
    layers.Dense(1, activation='sigmoid')
])

# TODO: Hiển thị summary của mô hình
model.summary()

/home/zhu/micromamba/lib/python3.12/site-packages/keras/src/layers/core/dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 16)             │           144 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 161 (644.00 B)

 Trainable params: 161 (644.00 B)

 Non-trainable params: 0 (0.00 B)

## Bài 8. Tạo dữ liệu giả cho bài toán phân loại nhị phân

Yêu cầu:

1. Dùng NumPy tạo `x_train` gồm 200 mẫu, mỗi mẫu có 8 đặc trưng ngẫu nhiên.
2. Tạo `y_train` theo quy tắc: nếu tổng 8 đặc trưng > 4 thì gán nhãn 1, ngược lại nhãn 0.
3. Tạo tương tự `x_test` gồm 50 mẫu và `y_test`.
4. In shape của `x_train`, `y_train`, `x_test`, `y_test`.

In [32]:
# TODO: Đặt random seed để kết quả có thể tái lập
np.random.seed(42)

# TODO: Tạo x_train và y_train
x_train = np.random.rand(200, 8)
y_train = (np.sum(x_train, axis=1) > 4).astype('float32')

# TODO: Tạo x_test và y_test
x_test = np.random.rand(50, 8)
y_test = (np.sum(x_test, axis=1) > 4).astype('float32')

# TODO: In shape của các tập dữ liệu
print("Shape of x_train:", x_train.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of x_test:", x_test.shape)
print("Shape of y_test:", y_test.shape)

Shape of x_train: (200, 8)
Shape of y_train: (200,)
Shape of x_test: (50, 8)
Shape of y_test: (50,)


## Bài 9. Compile và huấn luyện mô hình

Yêu cầu:

1. Compile model với:
   - optimizer = `rmsprop`
   - loss = `binary_crossentropy`
   - metrics = `accuracy`
2. Train mô hình với:
   - epochs = 5
   - batch_size = 16
   - validation_split = 0.2
3. Lưu lịch sử train vào biến `history`.

In [34]:
# TODO: Compile mô hình
model.compile(
    optimizer='rmsprop',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# TODO: Huấn luyện mô hình và lưu vào biến history
history = model.fit(
    x_train, y_train,
    epochs=5,
    batch_size=16,
    validation_split=0.2
)

Epoch 1/5


2026-04-09 16:18:42.540417: I external/local_xla/xla/service/service.cc:163] XLA service 0x7c6b88018300 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2026-04-09 16:18:42.540443: I external/local_xla/xla/service/service.cc:171]   StreamExecutor device (0): NVIDIA RTX A2000 8GB Laptop GPU, Compute Capability 8.6
2026-04-09 16:18:42.598334: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2026-04-09 16:18:42.769289: I external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:473] Loaded cuDNN version 91002


 7/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5549 - loss: 0.6373

I0000 00:00:1775726323.422312   49338 device_compiler.h:196] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


10/10 ━━━━━━━━━━━━━━━━━━━━ 2s 111ms/step - accuracy: 0.5250 - loss: 0.6715 - val_accuracy: 0.4000 - val_loss: 0.7212
Epoch 2/5
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5375 - loss: 0.6669 - val_accuracy: 0.4000 - val_loss: 0.7167
Epoch 3/5
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.5437 - loss: 0.6633 - val_accuracy: 0.4250 - val_loss: 0.7132
Epoch 4/5
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.5437 - loss: 0.6605 - val_accuracy: 0.4250 - val_loss: 0.7090
Epoch 5/5
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5437 - loss: 0.6580 - val_accuracy: 0.4250 - val_loss: 0.7053


## Bài 10. Đánh giá mô hình và dự đoán

Yêu cầu:

1. Đánh giá mô hình trên tập test.
2. In ra `test_loss` và `test_accuracy`.
3. Dự đoán xác suất cho 5 mẫu đầu tiên của `x_test`.
4. In kết quả dự đoán.
5. Hãy cho biết: nếu output sigmoid >= 0.5 thì thuộc lớp nào?

In [35]:
# TODO: Đánh giá mô hình trên tập test
test_loss, test_acc = model.evaluate(x_test, y_test, verbose=0)

# TODO: In test_loss và test_accuracy
print('Test loss =', round(float(test_loss), 4))
print('Test accuracy =', round(float(test_acc), 4))

# TODO: Dự đoán xác suất cho 5 mẫu đầu tiên
pred = model.predict(x_test[:5])

# TODO: In kết quả dự đoán
print('Predicted probabilities for first 5 test samples:')
print(pred)

Test loss = 0.6767
Test accuracy = 0.52
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 435ms/step
Predicted probabilities for first 5 test samples:
[[0.54316205]
 [0.5603821 ]
 [0.57334936]
 [0.53331196]
 [0.555307  ]]


## Bài 11. Câu hỏi tự luận ngắn

Hãy trả lời ngắn gọn các câu hỏi sau ngay trong ô Markdown bên dưới:

1. Vì sao TensorFlow phù hợp cho Deep Learning hơn NumPy?
2. `tf.Variable` khác gì với tensor hằng?
3. `GradientTape()` có vai trò gì trong huấn luyện mô hình?
4. Trong Keras, `compile()` và `fit()` khác nhau như thế nào?

### Trả lời của sinh viên

- Câu 1:
    
    TensorFlow được thiết kế để tối ưu hóa hiệu suất và khả năng mở rộng cho các mô hình Deep Learning lớn, trong khi NumPy chủ yếu tập trung vào tính toán mảng và không hỗ trợ GPU hoặc phân tán tính toán. 
    
    TensorFlow cung cấp các công cụ và API mạnh mẽ để xây dựng, huấn luyện và triển khai các mô hình Deep Learning phức tạp, trong khi NumPy chỉ là một thư viện tính toán mảng cơ bản.

- Câu 2:
    
    `tf.Variable` là một đối tượng có thể thay đổi giá trị trong quá trình huấn luyện, trong khi tensor hằng (constant) có giá trị cố định và không thể thay đổi sau khi được tạo ra. 
    
    Biến (`tf.Variable`) thường được sử dụng để lưu trữ trọng số của mô hình, còn tensor hằng thường được sử dụng để lưu trữ dữ liệu đầu vào hoặc các hằng số khác.

- Câu 3:

    `GradientTape()` là một công cụ trong TensorFlow giúp theo dõi các phép tính để tính toán gradient. Nó cho phép bạn ghi lại các phép tính và sau đó sử dụng thông tin này để tính toán gradient của một hàm mất mát đối với các biến huấn luyện. 
    
    Điều này rất hữu ích trong quá trình huấn luyện mô hình, vì nó giúp cập nhật trọng số của mô hình dựa trên gradient descent hoặc các thuật toán tối ưu hóa khác.

- Câu 4:

    `compile()` là bước cấu hình mô hình, nơi bạn chỉ định optimizer, loss function và metrics. Nó thiết lập cách mà mô hình sẽ được huấn luyện.
    
    `fit()` là bước thực sự huấn luyện mô hình trên dữ liệu. Nó nhận vào dữ liệu huấn luyện, số epoch, batch size và các tham số khác để bắt đầu quá trình học. `fit()` sẽ sử dụng cấu hình đã thiết lập trong `compile()` để cập nhật trọng số của mô hình dựa trên dữ liệu huấn luyện.

## Bài 12. Bài tập mở rộng

Yêu cầu:

Hãy thay đổi một trong các yếu tố sau và quan sát kết quả huấn luyện:

- Số neuron ở hidden layer: 16 → 32
- Số epoch: 5 → 10
- Batch size: 16 → 8 hoặc 32

Viết nhận xét ngắn: Việc thay đổi đó có ảnh hưởng gì đến kết quả train hoặc test?

In [3]:
# TODO: Thử thay đổi một tham số huấn luyện hoặc kiến trúc mô hình
# Gợi ý: tạo lại model, compile lại, train lại và so sánh kết quả

np.random.seed(42)
x_train = np.random.rand(200, 8)
y_train = (np.sum(x_train, axis=1) > 4).astype('float32')
x_test = np.random.rand(50, 8)
y_test = (np.sum(x_test, axis=1) > 4).astype('float32')

model = keras.Sequential([
    layers.Dense(32, activation='relu', input_shape=(8,)),
    layers.Dense(1, activation='sigmoid')
])
model.summary()

model.compile(
    optimizer='rmsprop',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    x_train, y_train,
    epochs=10,
    batch_size=32,
    validation_split=0.2
)

test_loss, test_acc = model.evaluate(x_test, y_test, verbose=0)
print('Test loss =', round(float(test_loss), 4))
print('Test accuracy =', round(float(test_acc), 4))

pred = model.predict(x_test[:5])
print('Predicted probabilities for first 5 test samples:')
print(pred)

/home/zhu/micromamba/lib/python3.12/site-packages/keras/src/layers/core/dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
I0000 00:00:1775726913.729486  104391 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 6203 MB memory:  -> device: 0, name: NVIDIA RTX A2000 8GB Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/10


2026-04-09 16:28:35.539558: I external/local_xla/xla/service/service.cc:163] XLA service 0x73fe38006d30 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2026-04-09 16:28:35.539574: I external/local_xla/xla/service/service.cc:171]   StreamExecutor device (0): NVIDIA RTX A2000 8GB Laptop GPU, Compute Capability 8.6
2026-04-09 16:28:35.565962: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2026-04-09 16:28:35.715748: I external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:473] Loaded cuDNN version 91002


1/5 ━━━━━━━━━━━━━━━━━━━━ 6s 2s/step - accuracy: 0.5625 - loss: 0.7363

I0000 00:00:1775726916.555452  105528 device_compiler.h:196] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


5/5 ━━━━━━━━━━━━━━━━━━━━ 3s 264ms/step - accuracy: 0.4688 - loss: 0.7631 - val_accuracy: 0.5500 - val_loss: 0.7087
Epoch 2/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.4688 - loss: 0.7327 - val_accuracy: 0.4500 - val_loss: 0.7054
Epoch 3/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.4563 - loss: 0.7163 - val_accuracy: 0.4500 - val_loss: 0.7047
Epoch 4/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.4812 - loss: 0.7041 - val_accuracy: 0.4500 - val_loss: 0.7056
Epoch 5/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.4812 - loss: 0.6948 - val_accuracy: 0.4750 - val_loss: 0.7072
Epoch 6/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.4875 - loss: 0.6878 - val_accuracy: 0.5250 - val_loss: 0.7082
Epoch 7/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5250 - loss: 0.6826 - val_accuracy: 0.5250 - val_loss: 0.7095
Epoch 8/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5688 - loss: 0.6772 - val_accuracy: 0.5250 - val_loss: 0.7114
Epoch 9/10

### Nhận xét của sinh viên

    Việc tăng số neuron ở hidden layer từ 16 lên 32 giúp mô hình có khả năng học được nhiều đặc trưng hơn từ dữ liệu, điều này có thể cải thiện độ chính xác của mô hình. 

    Tăng số epoch từ 5 lên 10 cho phép mô hình có thêm thời gian để học và tối ưu hóa, điều này cũng có thể dẫn đến kết quả tốt hơn. 

    Thay đổi batch size từ 16 lên 32 có thể giúp quá trình huấn luyện ổn định hơn và nhanh hơn, nhưng cũng có thể làm giảm khả năng tổng quát hóa của mô hình nếu batch size quá lớn. 

    Tổng thể, những thay đổi này thường sẽ cải thiện hiệu suất của mô hình trên tập test, nhưng cũng cần phải thử nghiệm để tìm ra cấu hình tốt nhất.

## Kết thúc bài thực hành

Sau khi hoàn thành notebook này, sinh viên cần nộp lại file `.ipynb` đã điền đầy đủ lời giải và kết quả chạy.