# Tuần 3 - Bài tập

Notebook này gồm các nội dung:
- Tạo tensor bằng NumPy và thực hiện các phép toán trên tensor.
- Slicing tensor.
- Dùng neural network có hai lớp ẩn để phân loại nhị phân.
- Dùng neural network có hai lớp ẩn để phân loại đa loại.


## Phần 1. Tạo tensor bằng NumPy và thực hiện các phép toán trên tensor

### Câu 1
Import thư viện NumPy với bí danh là `np`.

In [1]:
import numpy as np

### Câu 2
Tạo một tensor 1 chiều gồm các phần tử: 1, 2, 3, 4, 5.

In [12]:
a = np.array([1, 2, 3, 4, 5])
print("Dim of a:", a.ndim)
print("Shape of a:", a.shape)
print("Size of a:", a.size)
print("Data type of a:", a.dtype)
a

Dim of a: 1
Shape of a: (5,)
Size of a: 5
Data type of a: int64


array([1, 2, 3, 4, 5])

### Câu 3
Tạo hai tensor 2 chiều kích thước 2x2 bất kỳ.

In [ ]:
A = np.random.rand(2, 2)
B = np.random.rand(2, 2)
print("Tensor A:\n", A)
print("Tensor B:\n", B)

Tensor A:
 [[0.26452198 0.44324954]
 [0.37928106 0.24792642]]
Tensor B:
 [[0.46571075 0.62056794]
 [0.73284195 0.25659469]]


### Câu 4
Thực hiện các phép toán cộng, trừ, nhân từng phần tử giữa hai tensor 2 chiều đã tạo.

In [ ]:
print("A + B:\n", A + B)
print("A - B:\n", A - B)
print("A * B:\n", A * B)

A + B:
 [[0.73023273 1.06381747]
 [1.11212301 0.50452111]]
A - B:
 [[-0.20118878 -0.1773184 ]
 [-0.35356089 -0.00866827]]
A * B:
 [[0.12319073 0.27506645]
 [0.27795307 0.0636166 ]]


### Câu 5
Thực hiện phép nhân ma trận giữa hai tensor 2 chiều.

In [16]:
print("A @ B:\n", A @ B)

A @ B:
 [[0.44802258 0.27788933]
 [0.35832615 0.29898627]]


### Câu 6
Tính tổng, giá trị trung bình, giá trị lớn nhất và giá trị nhỏ nhất của một tensor.

In [17]:
print("Sum of A:", np.sum(A))
print("Mean of A:", np.mean(A))
print("Max of A:", np.max(A))
print("Min of A:", np.min(A))

Sum of A: 1.334978997575941
Mean of A: 0.33374474939398524
Max of A: 0.4432495386341567
Min of A: 0.2479264235933457


## Phần 2. Slicing tensor

### Câu 7
Tạo tensor 2 chiều sau bằng NumPy:

$$\begin{bmatrix}
10 & 20 & 30 & 40 \\
50 & 60 & 70 & 80 \\
90 & 100 & 110 & 120
\end{bmatrix}$$

In [23]:
ts = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]])
print("Tensor:\n", ts)

Tensor:
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


### Câu 8
Lấy hàng thứ 2 của tensor.

In [26]:
print("2nd row:", ts[1])

2nd row: [50 60 70 80]


### Câu 9
Lấy cột thứ 3 của tensor.

In [ ]:
print("3rd column:", ts[:, 2])

3rd column: [ 30  70 110]


### Câu 10
Lấy ma trận con gồm 2 hàng đầu và 3 cột đầu.

In [28]:
print("Matrix 2 first rows and 3 first cols:\n", ts[:2, :3])

Matrix 2 first rows and 3 first cols:
 [[10 20 30]
 [50 60 70]]


### Câu 11
Lấy 2 phần tử cuối của mỗi hàng.

In [29]:
print("2 last each rows:\n", ts[:, -2:])

2 last each rows:
 [[ 30  40]
 [ 70  80]
 [110 120]]


### Câu 12
Lấy phần tử nằm ở hàng 3, cột 2.

In [30]:
print("num at row 3 col 2:", ts[2, 1])

num at row 3 col 2: 100


## Phần 3. Neural network có hai lớp ẩn để phân loại nhị phân

### Câu 13
Import các thư viện cần thiết để:
- tạo 1000 dòng dữ liệu phân loại nhị phân có 5 đặc trưng, giá trị dữ liệu $ \in [0,100]$,
- chia tập train/test,
- chuẩn hóa dữ liệu về [0,1],
- xây dựng mô hình neural network bằng Keras.

In [35]:
import numpy as np
from sklearn.datasets import make_classification
# Data splitting
from sklearn.model_selection import train_test_split
# Normalization về [0, 1]
from sklearn.preprocessing import StandardScaler
# Neural network
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

### Câu 14
Tạo bộ dữ liệu phân loại nhị phân bằng `make_classification` với 1000 mẫu và 20 đặc trưng.

In [37]:
X, y = make_classification(n_samples=1000, n_features=20, n_classes=2, random_state=42)

### Câu 15
Chia dữ liệu thành tập huấn luyện và tập kiểm tra với tỉ lệ 80:20.

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

### Câu 16
Chuẩn hóa dữ liệu đầu vào bằng `StandardScaler`.

In [ ]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

### Câu 17
Xây dựng mô hình neural network có:
- 2 lớp ẩn,
- lớp ẩn thứ nhất có 32 neuron,
- lớp ẩn thứ hai có 16 neuron,
- hàm kích hoạt `relu`,
- lớp đầu ra phù hợp cho bài toán phân loại nhị phân.

In [ ]:
model = keras.Sequential([
    layers.Dense(32, activation='relu', input_shape=(20,)),
    layers.Dense(16, activation='relu'),
    layers.Dense(1, activation='sigmoid') #binary classification
])

/home/zhu/micromamba/lib/python3.12/site-packages/keras/src/layers/core/dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
E0000 00:00:1775121594.603696   80237 cuda_executor.cc:1309] INTERNAL: CUDA Runtime error: Failed call to cudaGetRuntimeVersion: Error loading CUDA libraries. GPU will not be used.: Error loading CUDA libraries. GPU will not be used.
W0000 00:00:1775121595.383245   80237 gpu_device.cc:2342] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


### Câu 18
Biên dịch mô hình với:
- optimizer: `adam`
- loss phù hợp cho phân loại nhị phân
- metric: `accuracy`

In [39]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

### Câu 19
Huấn luyện mô hình trong 20 epoch với batch size bằng 32 và dùng 20% tập train làm validation.

In [40]:
model.fit(X_train_scaled, y_train, epochs=20, batch_size=32, validation_split=0.2)

Epoch 1/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - accuracy: 0.6062 - loss: 0.6615 - val_accuracy: 0.6562 - val_loss: 0.6203
Epoch 2/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7078 - loss: 0.5890 - val_accuracy: 0.7688 - val_loss: 0.5490
Epoch 3/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7719 - loss: 0.5291 - val_accuracy: 0.8188 - val_loss: 0.4893
Epoch 4/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8078 - loss: 0.4762 - val_accuracy: 0.8500 - val_loss: 0.4350
Epoch 5/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8281 - loss: 0.4334 - val_accuracy: 0.8500 - val_loss: 0.3924
Epoch 6/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8391 - loss: 0.3981 - val_accuracy: 0.8438 - val_loss: 0.3643
Epoch 7/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8531 - loss: 0.3718 - val_accuracy: 0.8625 - val_loss: 0.3371
Epoch 8/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8594 - loss: 0.3499 - val_accuracy: 0.8750 - val

### Câu 20
Đánh giá mô hình trên tập test và in ra loss, accuracy.

In [41]:
test_loss, test_acc = model.evaluate(X_test_scaled, y_test)
print("Test Loss:", test_loss)
print("Test Accuracy:", test_acc)

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8550 - loss: 0.3594 
Test Loss: 0.3594008982181549
Test Accuracy: 0.8550000190734863


## Phần 4. Neural network có hai lớp ẩn để phân đa loại

### Câu 21
Import các thư viện cần thiết để làm bài toán phân loại đa loại với bộ dữ liệu Iris.

In [1]:
# Importing libraries to do Iris dataset classification
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

2026-04-02 23:51:58.440339: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2026-04-02 23:51:58.451308: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-04-02 23:51:58.868723: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-04-02 23:52:00.099628: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off,

### Câu 22
Tải bộ dữ liệu Iris và gán dữ liệu đầu vào cho `X`, nhãn cho `y`.

In [2]:
#Loading Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

### Câu 23
- One-hot vector là gì?

    One-hot vector (hay One-hot encoding) là một phương pháp biểu diễn các dữ liệu phân loại (categorical data) dưới dạng các vector số học để máy tính và các thuật toán học máy có thể hiểu được.
    
    Cấu trúc của một One-hot vector rất đơn giản: đó là một vector mà trong đó chỉ có duy nhất một phần tử có giá trị là 1, tất cả các phần tử còn lại đều có giá trị là 0.

- Chuyển nhãn `y` sang dạng one-hot encoding.

In [3]:
#Turn y into one-hot encoding
y = keras.utils.to_categorical(y, num_classes=3)

### Câu 24
Chia dữ liệu thành tập huấn luyện và tập kiểm tra với tỉ lệ 80:20.

In [4]:
#Splitting data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

### Câu 25
Chuẩn hóa dữ liệu đầu vào.

In [5]:
#Normalizing dataset features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

### Câu 26
Xây dựng mô hình neural network có:
- 2 lớp ẩn,
- lớp ẩn thứ nhất có 16 neuron,
- lớp ẩn thứ hai có 8 neuron,
- hàm kích hoạt `relu`,
- lớp đầu ra phù hợp cho bài toán phân loại 3 lớp.

In [6]:
# Building a simple neural network model
# Two hidden layers with 16 and 8 neurons, activation with RELU ,and an output layer with 3 neurons for 3 classes
model = keras.Sequential([
    layers.Dense(16, activation='relu', input_shape=(4,)),
    layers.Dense(8, activation='relu'),
    layers.Dense(3, activation='softmax') #multi-class classification
])

/home/zhu/micromamba/lib/python3.12/site-packages/keras/src/layers/core/dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
E0000 00:00:1775149054.593745  117762 cuda_executor.cc:1309] INTERNAL: CUDA Runtime error: Failed call to cudaGetRuntimeVersion: Error loading CUDA libraries. GPU will not be used.: Error loading CUDA libraries. GPU will not be used.
W0000 00:00:1775149055.173644  117762 gpu_device.cc:2342] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


### Câu 27
Biên dịch mô hình với:
- optimizer: `adam`
- loss phù hợp cho phân loại đa loại
- metric: `accuracy`

In [7]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

### Câu 28
Huấn luyện mô hình trong 30 epoch với batch size bằng 16 và dùng 20% tập train làm validation.

In [8]:
model.fit(X_train_scaled, y_train, epochs=30, batch_size=16, validation_split=0.2)

Epoch 1/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - accuracy: 0.2083 - loss: 1.1067 - val_accuracy: 0.1250 - val_loss: 1.0277
Epoch 2/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.1875 - loss: 1.0684 - val_accuracy: 0.2500 - val_loss: 0.9892
Epoch 3/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.2708 - loss: 1.0330 - val_accuracy: 0.3333 - val_loss: 0.9520
Epoch 4/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.3542 - loss: 1.0029 - val_accuracy: 0.3750 - val_loss: 0.9142
Epoch 5/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.3958 - loss: 0.9723 - val_accuracy: 0.4583 - val_loss: 0.8810
Epoch 6/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.3854 - loss: 0.9452 - val_accuracy: 0.5000 - val_loss: 0.8485
Epoch 7/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.3854 - loss: 0.9204 - val_accuracy: 0.5000 - val_loss: 0.8190
Epoch 8/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4062 - loss: 0.8965 - val_accuracy: 0.5417 - val_loss: 0.7917
Epoch 9

### Câu 29
Đánh giá mô hình trên tập test và in ra loss, accuracy.

In [9]:
# Rate the model on the test set, show loss and accuracy
test_loss, test_acc = model.evaluate(X_test_scaled, y_test)
print("Test Loss:", test_loss)
print("Test Accuracy:", test_acc)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9667 - loss: 0.3961
Test Loss: 0.3960740268230438
Test Accuracy: 0.9666666388511658


## Phần 5. Câu hỏi tự luận

### Câu 30
Tensor là gì? Tensor khác gì so với vector và ma trận?

Tensor là một thuật ngữ toán học dùng để chỉ một khối dữ liệu số có n chiều (thường từ 3 chiều trở lên). Trong đó, tensor là một sự tổng quát hóa của các khái niệm quen thuộc như scalar, vector và ma trận.

Ma trận được cho là một Tensor hai chiều. Sự khác biệt của cả hai nằm ở cấu trúc. Trong khi ma trận chỉ có hai hướng phát triển là chiều dài và rộng trên bề mặt không gian 2D. Tensor có thể mở rộng ra nhiều chiều hơn như chiều cao, độ sâu, thời gian,v.v... Hầu hết hiện nay như hình ảnh, âm thanh lưu trữ trên máy tính được vận hành dưới dạng Tensor. Điều này giúp người học về Data Science hay Artifacial Intelligence dễ xử lý dữ liệu hoặc giúp thuật toán máy móc học được dữ liệu.

### Câu 31

Vì sao cần chuẩn hóa dữ liệu trước khi huấn luyện neural network?

Việc chuẩn hóa dữ liệu giúp đưa các đặc trưng về cùng một thang đo, giúp quá trình huấn luyện ổn định hơn và nhanh hơn. Nếu dữ liệu có phạm vi giá trị khác nhau, các đặc trưng có giá trị lớn có thể chi phối quá trình học, dẫn đến việc mô hình khó học được các đặc trưng có giá trị nhỏ. Chuẩn hóa giúp cải thiện hiệu suất của mô hình và giảm thiểu nguy cơ bị mắc kẹt trong các điểm cực tiểu cục bộ.

### Câu 32
Vai trò của hàm kích hoạt trong mạng neural network là gì?

Hàm kích hoạt (activation function) trong mạng neural network có vai trò quan trọng trong việc giúp mô hình học được các mối quan hệ phi tuyến tính giữa các đặc trưng của dữ liệu. Nếu không có hàm kích hoạt, mạng neural sẽ chỉ có thể học được các mối quan hệ tuyến tính, điều này sẽ hạn chế khả năng của mô hình trong việc giải quyết các bài toán phức tạp. Hàm kích hoạt giúp mô hình có thể học và biểu diễn các mối quan hệ phức tạp hơn, từ đó cải thiện hiệu suất của mô hình trên các bài toán thực tế.

### Câu 33
Khi nào nên dùng `sigmoid`, khi nào nên dùng `softmax`?

- Hàm `sigmoid` thường được sử dụng cho bài toán phân loại nhị phân (binary classification), nơi chỉ có hai lớp (ví dụ: 0 và 1). Nó trả về một giá trị trong khoảng [0, 1], biểu thị xác suất của lớp dương (positive class).

- Hàm `softmax` thường được sử dụng cho bài toán phân loại đa lớp (multi-class classification), nơi có nhiều hơn hai lớp. Nó trả về một vector xác suất, trong đó mỗi phần tử biểu thị xác suất của một lớp cụ thể, và tổng các phần tử trong vector này bằng 1.

### Câu 34
Mạng có nhiều lớp ẩn hơn có phải luôn tốt hơn không? Giải thích.

Mạng có nhiều lớp ẩn hơn không phải lúc nào cũng tốt hơn. Mặc dù mạng sâu có thể học được các đặc trưng phức tạp hơn, nhưng chúng cũng dễ bị overfitting nếu dữ liệu huấn luyện không đủ lớn hoặc không đủ đa dạng. Ngoài ra, việc huấn luyện mạng sâu cũng đòi hỏi nhiều tài nguyên tính toán hơn và có thể gặp khó khăn trong việc tối ưu hóa. Do đó, việc chọn số lượng lớp ẩn phù hợp phụ thuộc vào kích thước và tính chất của dữ liệu, cũng như mục tiêu của bài toán.