In [1]:
import numpy as np

r5 = np.array([11, 5.6, True, False, "mrTu"])

r5 , type(r5) , type(r5[2])

(array(['11', '5.6', 'True', 'False', 'mrTu'], dtype='<U32'),
 numpy.ndarray,
 numpy.str_)

In [3]:
# linspace
import numpy as np

l1 = np.linspace(0, 10, 5)
print(1, l1)

l2 = np.linspace(0, 10, 6)
print(2, l2)

1 [ 0.   2.5  5.   7.5 10. ]
2 [ 0.  2.  4.  6.  8. 10.]


In [4]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [6]:
m2 = np.ones((2,3,2))
m2

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [8]:
m2.ndim , m2.shape

(3, (2, 3, 2))

In [4]:
m3 = np.array([[[1., 2.],
        [3., 4.],
        [5., 6.]],

       [[7., 8.],
        [9., 10.],
        [11., 12.]]])

m3.ndim, m3.shape, m3

(3,
 (2, 3, 2),
 array([[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.]],
 
        [[ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]]))

In [5]:
m3.reshape(12)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [6]:
m3.reshape(4,3)

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [9]:
## Random

ssn = np.random.randn(30,30)

In [10]:
ssn.mean()

np.float64(0.03089080803367604)

In [11]:
np.random.randn(5)

array([ 0.91807185, -0.65177929,  1.02721225,  0.12404764,  1.31631224])

In [12]:
ppd = np.random.randn(100)

In [13]:
ppd.mean()

np.float64(0.15550114833969025)

## 1. Nêu các ý tưởng về đề tài sẽ làm cuối khóa

## 2. Làm tiếp logic của 4 số, ..

In [14]:
import random
import numpy as np