## 📖 Ôn tập cơ bản về NumPy

NumPy 🔢 (Numerical Python) là một thư viện cốt lõi của Python dùng để:

- Xử lý mảng số học (arrays) và ma trận.

- Thực hiện các phép toán toán học, đại số tuyến tính, xác suất thống kê rất nhanh nhờ được viết bằng C phía dưới.

- Là nền tảng cho nhiều thư viện khác: pandas, scikit-learn, TensorFlow, PyTorch…

### 1. Khởi tạo mảng (ndarray)
Bước cơ bản nhất là **khởi tạo mảng (ndarray)**, thường là tạo mảng từ một list có sẵn trong Python (**np.array()**).

- Tạo mảng 1D

In [1]:
# Bắt đầu bằng việc import thư viện NumPy với alias phổ biến là 'np'
import numpy as np

# Tạo mảng từ Python list
arr1 = np.array([1, 2, 3, 4, 5])
print("Mảng 1D:", arr1)

# Dùng arange (giống range của Python)
arr2 = np.arange(0, 10, 2)  # từ 0 đến <10, bước 2
print("Mảng 1D với arange:", arr2)

# Dùng linspace (chia đều khoảng)
arr3 = np.linspace(0, 1, 5)  # 5 giá trị từ 0 đến 1
print("Mảng 1D với linspace:", arr3)

Mảng 1D: [1 2 3 4 5]
Mảng 1D với arange: [0 2 4 6 8]
Mảng 1D với linspace: [0.   0.25 0.5  0.75 1.  ]


- Tạo mảng 2D

In [2]:
# Tạo mảng từ list lồng nhau
arr4 = np.array([[1, 2, 3],
                 [4, 5, 6]])
print("Mảng 2D:\n", arr4)

# Dùng zeros để tạo ma trận 2x3 toàn số 0
arr5 = np.zeros((2, 3))
print("Mảng zeros:\n", arr5)

# Dùng ones để tạo ma trận 3x2 toàn số 1
arr6 = np.ones((3, 2))
print("Mảng ones:\n", arr6)

# Tạo ma trận đơn vị 3x3
arr7 = np.eye(3)
print("Ma trận đơn vị:\n", arr7)

# Tạo mảng 2x3 chứa số thực ngẫu nhiên trong khoảng [0, 1) 
arr8 = np.random.rand(2, 3)
print("Mảng 2D chứa các số thực ngẫu nhiên thuộc [0, 1):\n", arr8)

# Tạo mảng 2D (3x4) gồm số nguyên ngẫu nhiên từ 10 đến 50
arr9 = np.random.randint(10, 51, size=(3, 4))
print("Mảng 2D chứa các số nguyên ngẫu nhiên thuộc [10, 50]:\n", arr9)

Mảng 2D:
 [[1 2 3]
 [4 5 6]]
Mảng zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Mảng ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Ma trận đơn vị:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Mảng 2D chứa các số thực ngẫu nhiên thuộc [0, 1):
 [[0.25051056 0.58860522 0.16471571]
 [0.74835786 0.16117854 0.32245583]]
Mảng 2D chứa các số nguyên ngẫu nhiên thuộc [10, 50]:
 [[31 23 44 10]
 [50 19 18 50]
 [50 31 13 19]]


### 2. Thuộc tính cơ bản
Chúng ta có thể kiểm tra các **thuộc tính cơ bản** của mảng, bao gồm **kích thước (arr.shape)** (số dòng, cột), **số chiều (arr.ndim)**, và **kiểu dữ liệu (arr.dtype)**.

In [3]:
A = np.random.rand(3, 2)

# Kích thước của mảng (3 dòng, 2 cột)
print("Kích thước (shape):", A.shape)

# Số chiều của mảng (2 chiều)
print("Số chiều (ndim):", A.ndim)

# Số phần tử của mảng (3 * 2 = 6)
print("Số phần tử (size):", A.size)

Kích thước (shape): (3, 2)
Số chiều (ndim): 2
Số phần tử (size): 6


### 3. Truy cập và cắt lát dữ liệu
Để trích xuất dữ liệu, ta sử dụng **truy cập phần tử (indexing)** (ví dụ: `arr`) và **cắt lát (slicing)**. Cú pháp `[:,1]` dùng để chọn tất cả các dòng ở cột thứ 1.

In [4]:
# Tạo mảng 2D (4x5) gồm số nguyên ngẫu nhiên từ 1 đến 50
data = np.random.randint(1, 51, size=(4, 5))
print("Dữ liệu:\n", data)

# Truy cập phần tử ở dòng 1, cột 2 
element = data[1, 2]
print("Phần tử:\n", element)

# Cắt lát: Lấy tất cả các dòng, chỉ lấy cột thứ 1 
column_slice = data[:, 1]
print("Cột thứ 1 (Index 1):\n", column_slice)

# Cắt lát: Lấy các phần tử thuộc dòng thứ 1 
row_slice = data[1]
print("Dòng thứ 1 (Index 1):\n", row_slice)

# Cắt lát nâng cao: Lấy dòng 1 đến 3 (không bao gồm 3), cột 0 đến 2 (không bao gồm 2)
sub_array = data[1:3, 0:2]
print("Mảng con:\n", sub_array)

Dữ liệu:
 [[26 35 49  5 32]
 [40 17 21 24 42]
 [45 32 27 16 24]
 [36 44  6 45 33]]
Phần tử:
 21
Cột thứ 1 (Index 1):
 [35 17 32 44]
Dòng thứ 1 (Index 1):
 [40 17 21 24 42]
Mảng con:
 [[40 17]
 [45 32]]


### 4. Toán tử và phép tính mảng
NumPy hỗ trợ **phép toán phần tử (element-wise)** cơ bản như `+ - * /`. Ngoài ra, còn có nhiều **hàm toán học** tích hợp sẵn, ví dụ **np.sqrt()** (căn bậc hai).

In [5]:
# Tạo mảng 2D (2x3) gồm số nguyên ngẫu nhiên từ 1 đến 20
a = np.random.randint(1, 21, size=(2, 3))
b = np.random.randint(1, 21, size=(2, 3))
print("Nội dung 2 array:\n", a, "\n\n", b)

# Phép cộng phần tử (element-wise addition)
result_add = a + b
print("Kết quả cộng:\n", result_add)

# Phép nhân phần tử (element-wise multiplication)
result_mult = a * b
print("Kết quả nhân:\n", result_mult)

# Áp dụng hàm toán học (tính căn bậc hai cho từng phần tử)
result_sqrt = np.sqrt(b)
print("Kết quả căn bậc hai:\n", result_sqrt)

Nội dung 2 array:
 [[ 3  2  9]
 [ 4  1 19]] 

 [[ 4 13  1]
 [14  8  4]]
Kết quả cộng:
 [[ 7 15 10]
 [18  9 23]]
Kết quả nhân:
 [[12 26  9]
 [56  8 76]]
Kết quả căn bậc hai:
 [[2.         3.60555128 1.        ]
 [3.74165739 2.82842712 2.        ]]


### 5. Thống kê và tổng hợp
Các hàm **thống kê và tổng hợp** cho phép tính toán nhanh chóng như tổng (**arr.sum()**), giá trị trung bình (**arr.mean()**), hoặc vị trí của giá trị lớn nhất (**arr.argmax()**).

In [6]:
# Tạo mảng 2D (2x3) gồm số nguyên ngẫu nhiên từ 1 đến 20
stats_arr = np.random.randint(1, 21, size=(2, 3))
print("Array:\n", stats_arr)

# Tính tổng các phần tử
print("Tổng (sum):", stats_arr.sum())

# Tính giá trị trung bình
print("Trung bình (mean):", stats_arr.mean())

Array:
 [[ 3 19  4]
 [18 17  7]]
Tổng (sum): 68
Trung bình (mean): 11.333333333333334


Tìm vị trí (index) của giá trị nhỏ nhất

In [7]:
arr = np.array([[5, 2, 8],
                [7, 6, 1],
                [9, 3, 4]])

# argmin() trả về chỉ số như mảng 1D (flatten)
idx = np.argmin(arr)
print("Chỉ số (flatten):", idx)
# np.unravel_index() chuyển chỉ số 1D thành tọa độ 2D
print("Vị trí (dòng, cột):", np.unravel_index(idx, arr.shape))


Chỉ số (flatten): 5
Vị trí (dòng, cột): (np.int64(1), np.int64(2))


Khi tính toán thống kê trên mảng nhiều chiều, tham số **axis** quy định phạm vi tính toán: **axis=0** tính toán theo cột, còn **axis=1** tính toán theo dòng.

In [8]:
M = np.array([[5, 2, 8],
                [7, 6, 1],
                [9, 3, 4]])
print("Ma trận M:\n", M)

# Tổng theo cột (axis=0):  
sum_col = M.sum(axis=0)
print("Tổng theo cột (axis=0):", sum_col)

# Tổng theo dòng (axis=1):  
sum_row = M.sum(axis=1)
print("Tổng theo dòng (axis=1):", sum_row)

Ma trận M:
 [[5 2 8]
 [7 6 1]
 [9 3 4]]
Tổng theo cột (axis=0): [21 11 13]
Tổng theo dòng (axis=1): [15 14 16]


### 6. Thay đổi hình dạng mảng
Chúng ta có thể thay đổi kích thước mảng bằng **arr.reshape(dòng, cột)** hoặc làm phẳng mảng nhiều chiều thành 1D bằng **arr.flatten()**. **arr.T** dùng để **chuyển vị (transpose)**.

In [9]:
base_arr = np.arange(12)
print("Mảng ban đầu (1D):", base_arr)

# Đổi kích thước thành 3 dòng, 4 cột
reshaped_arr = base_arr.reshape(3, 4)
print("Mảng Reshaped (3x4):\n", reshaped_arr)

# Chuyển vị (dòng thành cột và ngược lại)
transposed_arr = reshaped_arr.T
print("Mảng Transposed (4x3):\n", transposed_arr)

# Chuyển mảng 2D thành 1D
arr = reshaped_arr.flatten()
print("Sau khi flatten():\n", arr)

Mảng ban đầu (1D): [ 0  1  2  3  4  5  6  7  8  9 10 11]
Mảng Reshaped (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Mảng Transposed (4x3):
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Sau khi flatten():
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


### 7. Ghép và Chia mảng
Để **ghép** mảng, ta sử dụng **np.concatenate()** hoặc các hàm chuyên biệt theo chiều dọc (**np.vstack()**) hoặc chiều ngang (**np.hstack()**).

In [10]:
a1 = np.ones((2, 2))
a2 = np.zeros((2, 2))

# Ghép hai array
arr_concatenate = np.concatenate([a1, a2])
print("Ghép (concatenate):\n", arr_concatenate)

# Ghép theo chiều dọc (Stacking Vertically)
vertical_stack = np.vstack([a1, a2])
print("Ghép dọc (vstack):\n", vertical_stack)

# Ghép theo chiều ngang (Stacking Horizontally)
horizontal_stack = np.hstack([a1, a2])
print("Ghép ngang (hstack):\n", horizontal_stack)

Ghép (concatenate):
 [[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]
Ghép dọc (vstack):
 [[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]
Ghép ngang (hstack):
 [[1. 1. 0. 0.]
 [1. 1. 0. 0.]]


### 8. Sinh số ngẫu nhiên
Module **numpy.random** rất quan trọng để mô phỏng dữ liệu. Ví dụ, **np.random.randint()** tạo ra các số nguyên ngẫu nhiên trong một phạm vi xác định. Việc sử dụng **np.random.seed()** giúp tái lập kết quả ngẫu nhiên.

In [11]:
# Thiết lập seed (giá trị mầm) để đảm bảo kết quả có thể lặp lại. 
# Seed giống nhau sẽ cho ra kết quả số ngẫu nhiên giống nhau giữa các lần tạo số ngẫu nhiên.
np.random.seed(42)

# Tạo mảng 3x3 chứa các số nguyên ngẫu nhiên từ 1 đến 9
random_matrix = np.random.randint(1, 10, (3, 3))
print("Ma trận ngẫu nhiên:\n", random_matrix)

# Tạo mảng 2x2 chứa số thực ngẫu nhiên trong khoảng [0, 1) 
random_uniform = np.random.rand(2, 2)
print("Số thực [0, 1):\n", random_uniform)

Ma trận ngẫu nhiên:
 [[7 4 8]
 [5 7 3]
 [7 8 5]]
Số thực [0, 1):
 [[0.60111501 0.70807258]
 [0.02058449 0.96990985]]
