# Bài Tập 1 (60 PHÚT)

## Nội dung
1. List, Tuple, Dictionary (20 phút)
2. NumPy (20 phút)
3. Pandas (20 phút)

## 1. List, Tuple, Dictionary (20 phút)

In [ ]:
# Bài 1: List cơ bản
# Tạo một list gồm 15 số nguyên bất kỳ
num = [5, 12, 3, 8, 20, 1, 15, 7, 9, 4, 18, 2, 10, 6, 11]

# 1. In ra phần tử lớn nhất, nhỏ nhất
max_num = max(num)
min_num = min(num)
print(f"Phần tử lớn nhất: {max_num}")
print(f"Phần tử nhỏ nhất: {min_num}")

# 2. Tính tổng các phần tử
total = sum(num)
print(f"Tổng các phần tử: {total}")

# 3. Đếm số lượng số chẵn
even_count = sum(1 for n in num if n % 2 == 0)
print(f"Số lượng số chẵn: {even_count}")

# 4. Tạo list mới chứa các số > 10
greater_than_10 = [n for n in num if n > 10]
print(f"Số lớn hơn 10: {greater_than_10}")

# TODO

Phần tử lớn nhất: 20
Phần tử nhỏ nhất: 1
Tổng các phần tử: 131
Số lượng số chẵn: 8
Số lớn hơn 10: [12, 20, 15, 18, 11]


In [ ]:
# Bài 2: Xử lý list nâng cao
# Cho list sau:
lst = [5, 2, 9, 1, 5, 6, 9, 2]

# 1. Loại bỏ phần tử trùng
unique_lst = list(set(lst))
print(f"List sau khi loại bỏ trùng: {unique_lst}")

# 2. Sắp xếp tăng dần
sorted_lst = sorted(lst)
print(f"List sau khi sắp xếp: {sorted_lst}")

# 3. Đảo ngược list
reversed_lst = lst[::-1]
print(f"List sau khi đảo ngược: {reversed_lst}")

# 4. Tìm số xuất hiện nhiều nhất
freq = {}
for num in lst:
    if num in freq:
        freq[num] += 1
    else:
        freq[num] = 1
max_count = max(freq.values())
most_frequent = [num for num in freq if freq[num] == max_count]
print(f"Số xuất hiện nhiều nhất: {most_frequent}")


# TODO

List sau khi loại bỏ trùng: [1, 2, 5, 6, 9]
List sau khi sắp xếp: [1, 2, 2, 5, 5, 6, 9, 9]
List sau khi đảo ngược: [2, 9, 6, 5, 1, 9, 2, 5]
Số xuất hiện nhiều nhất: [5, 2, 9]


In [ ]:
# Bài 3: Tuple
# Tạo tuple gồm 10 phần tử
my_tuple = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

# 1. Truy cập phần tử thứ 3
third_element = my_tuple[2]
print(f"Phần tử thứ 3: {third_element}")

# 2. Đếm số lần xuất hiện của một giá trị
value_to_count = 5
count = my_tuple.count(value_to_count)
print(f"Số lần xuất hiện của {value_to_count}: {count}")

# 3. Chuyển tuple sang list và thêm phần tử mới
lst_from_tuple = list(my_tuple)
lst_from_tuple.append(11)
print(f"List sau khi thêm phần tử mới: {lst_from_tuple}")

# TODO

Phần tử thứ 3: 3
Số lần xuất hiện của 5: 1
List sau khi thêm phần tử mới: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [ ]:
# Bài 4: Dictionary
# Tạo dictionary lưu thông tin 3 sinh viên
# Mỗi sinh viên gồm: name, age, score
students = {
    "student1": {"name": "Alice", "age": 20, "score": 8.5},
    "student2": {"name": "Bob", "age": 22, "score": 9.0},
    "student3": {"name": "Charlie", "age": 21, "score": 7.8}
}

# 1. In danh sách tên
names = [student["name"] for student in students.values()]
print(f"Danh sách tên: {names}")

# 2. Tìm sinh viên có điểm cao nhất
highest_score_student = max(students.values(), key=lambda s: s["score"])
print(f"Sinh viên có điểm cao nhất: {highest_score_student['name']} với điểm {highest_score_student['score']}")

# 3. Tính điểm trung bình
average_score = sum(student["score"] for student in students.values()) / len(students)
print(f"Điểm trung bình: {average_score}")

# 4. Thêm một sinh viên mới
students["student4"] = {"name": "David", "age": 23, "score": 8.8}
print(f"Thông tin sinh viên mới: {students['student4']}")

# TODO

Danh sách tên: ['Alice', 'Bob', 'Charlie']
Sinh viên có điểm cao nhất: Bob với điểm 9.0
Điểm trung bình: 8.433333333333334
Thông tin sinh viên mới: {'name': 'David', 'age': 23, 'score': 8.8}


## 2. NumPy (20 phút)

In [6]:
# Import numpy
import numpy as np
# TODO

In [ ]:
# Bài 5: Mảng 1 chiều
# Tạo mảng số nguyên gồm 20 phần tử
arr = np.array([1, 5, 3, 8, 2, 10, 6, 4, 9, 7, 12, 15, 11, 14, 13, 18, 17, 16, 20, 19])

# 1. Tính trung bình
mean = np.mean(arr)
print(f"Trung bình: {mean}")

# 2. Lọc các số chia hết cho 3
filtered_arr = arr[arr % 3 == 0]
print(f"Các số chia hết cho 3: {filtered_arr}")

# 3. Thay các số chẵn bằng 0
arr[arr % 2 == 0] = 0
print(f"Mảng sau khi thay các số chẵn bằng 0: {arr}")

# 4. Chuẩn hóa mảng (min-max scaling)
min_val = np.min(arr)
max_val = np.max(arr)
normalized_arr = (arr - min_val) / (max_val - min_val) if max_val != min_val else arr
print(f"Mảng sau khi chuẩn hóa: {normalized_arr}")

# TODO

Trung bình: 10.5
Các số chia hết cho 3: [ 3  6  9 12 15 18]
Mảng sau khi thay các số chẵn bằng 0: [ 1  5  3  0  0  0  0  0  9  7  0 15 11  0 13  0 17  0  0 19]
Mảng sau khi chuẩn hóa: [0.05263158 0.26315789 0.15789474 0.         0.         0.
 0.         0.         0.47368421 0.36842105 0.         0.78947368
 0.57894737 0.         0.68421053 0.         0.89473684 0.
 0.         1.        ]


In [ ]:
# Bài 6: Mảng 2 chiều
# Tạo ma trận 4x4 với giá trị ngẫu nhiên
matrix = np.random.randint(1, 10, (4, 4))
print(f"Ma trận 4x4:\n{matrix}")

# 1. Tính tổng từng hàng
row_sums = np.sum(matrix, axis=1)
print(f"Tổng từng hàng: {row_sums}")

# 2. Tính tổng từng cột
col_sums = np.sum(matrix, axis=0)
print(f"Tổng từng cột: {col_sums}")

# 3. Tìm phần tử lớn nhất
max_element = np.max(matrix)
print(f"Phần tử lớn nhất trong ma trận: {max_element}")

# 4. Tính định thức (nếu có thể)
det = np.linalg.det(matrix)
print(f"Định thức của ma trận: {det}")

# TODO

Ma trận 4x4:
[[4 1 8 7]
 [6 6 7 2]
 [4 6 2 1]
 [6 1 1 7]]
Tổng từng hàng: [20 21 13 15]
Tổng từng cột: [20 14 18 17]
Phần tử lớn nhất trong ma trận: 8
Định thức của ma trận: 751.9999999999994


## 3. Pandas (20 phút)

In [10]:
# Import pandas
import pandas as pd
# TODO

In [17]:
# Bài 7: Tạo DataFrame
# Tạo DataFrame gồm 5 sinh viên
# Các cột: name, age, score
data = {
    "name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "age": [20, 22, 21, 23, 19],
    "score": [8.5, 9.0, 5.5, 8.8, 9.2]
}
df = pd.DataFrame(data)
print(f"DataFrame:\n")
df
# TODO

DataFrame:



,name,age,score
0,Alice,20,8.5
1,Bob,22,9.0
2,Charlie,21,5.5
3,David,23,8.8
4,Eve,19,9.2


In [ ]:
# Bài 8: Xử lý dữ liệu
# 1. In 3 dòng đầu
print("3 dòng đầu của DataFrame:")
print(df.head(3))

# 2. Lọc sinh viên có score > 7
filtered_df = df[df["score"] > 7]
print(f"Sinh viên có điểm > 7:\n{filtered_df}")

# 3. Sắp xếp theo score giảm dần
sorted_df = df.sort_values(by="score", ascending=False)
print(f"DataFrame sau khi sắp xếp theo score giảm dần:\n{sorted_df}")

# 4. Tính điểm trung bình
average_score = df["score"].mean()
print(f"Điểm trung bình của sinh viên: {average_score}")

# TODO

3 dòng đầu của DataFrame:
      name  age  score
0    Alice   20    8.5
1      Bob   22    9.0
2  Charlie   21    5.5
Sinh viên có điểm > 7:
    name  age  score
0  Alice   20    8.5
1    Bob   22    9.0
3  David   23    8.8
4    Eve   19    9.2
DataFrame sau khi sắp xếp theo score giảm dần:
      name  age  score
4      Eve   19    9.2
1      Bob   22    9.0
3    David   23    8.8
0    Alice   20    8.5
2  Charlie   21    5.5
Điểm trung bình của sinh viên: 8.2


In [ ]:
# Bài 9: Nâng cao
# 1. Thêm cột 'result' theo điều kiện:
#    >= 8: Giỏi
#    >= 6.5: Khá
#    còn lại: Trung bình
def classify_score(score):
    if score >= 8:
        return "Giỏi"
    elif score >= 6.5:
        return "Khá"
    else:
        return "Trung bình"
df["result"] = df["score"].apply(classify_score)
print(f"DataFrame sau khi thêm cột 'result':\n{df}")

# 2. Đếm số lượng mỗi loại
result_counts = df["result"].value_counts()
print(f"Số lượng mỗi loại:\n{result_counts}")

# 3. Xuất DataFrame ra file CSV
df.to_csv("students.csv", index=False)
print("DataFrame đã được xuất ra file 'students.csv'.")

# TODO

DataFrame sau khi thêm cột 'result':
      name  age  score      result
0    Alice   20    8.5        Giỏi
1      Bob   22    9.0        Giỏi
2  Charlie   21    5.5  Trung bình
3    David   23    8.8        Giỏi
4      Eve   19    9.2        Giỏi
Số lượng mỗi loại:
result
Giỏi          4
Trung bình    1
Name: count, dtype: int64
DataFrame đã được xuất ra file 'students.csv'.
