Exercise 1: Creating Arrays with `arange`

Question: Use `numpy.arange` to create a 1D array of even numbers from 10 to 20 (inclusive of 10, exclusive of 20) with a step of 2. Print the array and its data type.

In [2]:
import numpy as np

A = np.arange(10, 20, 2)
print("10 to 20 (step 2) Array:",A)
print("Array type:",A.dtype)

10 to 20 (step 2) Array: [10 12 14 16 18]
Array type: int64


Exercise 2: Array Attributes

Question: Create a 2×3 array of your choice and print its `shape`, `size`, `ndim` (number of dimensions), and `dtype`.

In [9]:
B = np.random.rand(2,3)
print("Array:", B)
print("Shape:", B.shape)
print("Ndim:", B.ndim)
print("Size:", B.size)
print("Array types:", B.dtype)

Array: [[0.73730538 0.15337937 0.81134446]
 [0.11830374 0.89726165 0.43406782]]
Shape: (2, 3)
Ndim: 2
Size: 6
Array types: float64


Exercise 3: Arithmetic Operations

Question: Create two 1D arrays `a = [1, 2, 3]` and `b = [4, 5, 6]`. Perform element-wise addition, multiplication, and exponentiation. Also compute the matrix dot product.

In [12]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print("Addition of a anb b:", np.add(a,b))
print("Multiplication of a and b:", np.multiply(a,b))
print("Exponentiation of a and b:", np.power(a,b))
print("Matrix dot:", np.dot(a,b))

Addition of a anb b: [5 7 9]
Multiplication of a and b: [ 4 10 18]
Exponentiation of a and b: [  1  32 729]
Matrix dot: 32


Exercise 4: Indexing and Slicing

Question: Given the 2D array `matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])`, extract:

1. The element in the second row, third column.

2. The first two rows.

3. All elements from the last column.

In [14]:
matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print("The element in the second row, third column:", matrix[1,2])
print("The first two rows:",matrix[:2])
print("All elements from the last column:", matrix[:,-1])

The element in the second row, third column: 60
The first two rows: [[10 20 30]
 [40 50 60]]
All elements from the last column: [30 60 90]


Exercise 5: Universal Functions (ufunc)

Question: Create a 1D array of numbers from 1 to 5. Apply the `np.sqrt` and `np.exp` universal functions to it.

In [16]:
c = np.arange(1,6)

print("Square of c:", np.sqrt(c))
print("Exponential of c:", np.exp(c))

Square of c: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential of c: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


Exercise 6: Aggregate Functions

Question: Given the array `arr = np.array([15, 22, 8, 19, 27])`, compute the sum, mean, maximum, and standard deviation.

In [18]:
arr = np.array([15, 22, 8, 19, 27])

print("Sum of array:",np.sum(arr))
print("Mean of array:",np.mean(arr))
print("Maximum of array:",np.max(arr))
print("Standard deviation of array:",np.std(arr))

Sum of array: 91
Mean of array: 18.2
Maximum of array: 27
Standard deviation of array: 6.43117407632541


Exercise 7: Boolean Indexing

Question: From the array `arr = np.array([5, 12, 8, 3, 15, 7])`, extract all elements greater than 8.

In [19]:
arr = np.array([5, 12, 8, 3, 15, 7])

print("Elements greater than 8:", arr[arr > 8])

Elements greater than 8: [12 15]


Exercise 8: Shape Manipulation

Question: Create a 1D array with values from 0 to 11. Reshape it into a 3×4 matrix. Then flatten it back using `ravel()`.

In [10]:
arr = np.arange(0,12)
print(arr)

arr1 = np.reshape(arr,(3,4))
print("\nReshape array to 3x4:\n", arr1)
print("\nFlatten array back:", np.ravel(arr1))

[ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshape array to 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flatten array back: [ 0  1  2  3  4  5  6  7  8  9 10 11]


Exercise 9: Stacking Arrays

Question: Create two 2×2 arrays `a = [[1, 2], [3, 4]]` and `b = [[5, 6], [7, 8]]`. Stack them vertically and horizontally.

In [19]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("Vertical stack 2 array:\n", np.vstack([a,b]))
print("Horizontal stack 2 array:\n", np.hstack([a,b]))

Vertical stack 2 array:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal stack 2 array:
 [[1 2 5 6]
 [3 4 7 8]]


Exercise 10: Structured Arrays

Question: Create a structured array to store information about students: `name` (string of max 10 chars), `age` (int), and `grade` (float). Add at least two entries and print the names and ages.

In [20]:
dtype = np.dtype([
    ('name',  'U10'),   # Unicode string, max 10 chars
    ('age',   'i4'),    # 32-bit integer
    ('grade', 'f4')     # 32-bit float
])

students = np.array([
    ('Alice',   20, 88.5),
    ('Bob',     22, 91.0)
], dtype=dtype)

print(students['name'])
print(students['age'])

['Alice' 'Bob']
[20 22]
